services:
  - docker

language: node_js

node_js:
  - "11"

before_install:
  - docker-compose build

jobs:
  include:
    - stage: test
      script: docker-compose run api npm test
    - stage: test
      script: docker-compose run web npm test

deploy:
  provider: script
  script: chmod +x ./devops/bin/travis_deploy.sh && ./devops/bin/travis_deploy.sh
  on:
    branch: master
